### ISSUE TITLE
Roboto-regular and bold contain redundant cmap_format_12 table?

### ISSUE THREAD

**Issue by Ziriax** [google/roboto#104]
When inspected using Google's TTX, the Roboto Regular and Bold fonts contain a cmap_format_12 table.

However, the content of this table is exactly the same as the cmap_format_4 table.

Furthermore, the presence of this table seems to cause problems with the Win32 API CreateFontPackage

**Comment by jamesgk** [comment]
They're almost exactly the same, but actually the format 12 table contains two glyphs outside the Unicode BMP which can't be included in a format 4 table: uni1F16A and uni1F16B.

I'd be surprised if that API doesn't support format 12 tables. But one solution might be to try subsetting the TTFs using [nototools](https://github.com/googlei18n/nototools/blob/master/nototools/subset.py).

**Comment by moyogo** [comment]
@Ziriax what are the problems you see with Win32 API CreateFontPackage?

**Comment by Ziriax** [comment]
That is strange, when comparing these tables with TTX, I did not see these glyphs in the table. Also, the italic faces do not have these tables. I will double check tomorrow. 

When subsetting the font using that API call, the subset does not render at all in Google Chrome, but it does work in IE11 or DirectWrite. The subsetted italic faces work fine.

I will check out nonotools, thanks for the link!
