### ISSUE TITLE
Backwards compatible font metrics

### ISSUE THREAD

**Issue by jamesathey** [google/roboto#106]
As the Roboto family changes and grows over time, are the metrics maintained to preserve backwards compatibility? Do any of these changes cause text composed of valid glyphs to flow differently or have a different bounding box?

In other words, can an Android app that's compatible with ICS (API 14) and up use Roboto for its text and trust that the labels will take the same amount of space on ICS and Lollipop? Provided, of course, that the screens have the same properties (dpi, dimensions, resolution, etc.)

A system font is effectively part of a windowing system's public API. If the metrics change, then an app which is coded to expect a piece of text to fit within a certain box may break.

The Roboto font is as fundamental to Android as Arial and Verdana are to Windows. [As Microsoft puts it](https://msdn.microsoft.com/en-us/library/windows/desktop/Dn614134(v=VS.85).aspx),

> Note that some values associated with UI fonts and default fonts used in Microsoft apps are locked. UI fonts are used to render UI elements like captions, dialogs, and menus. Very few changes are made to these fonts, given their high visibility and frequent use.

**Comment by roozbehp** [comment]
I understand that metric compatibility would be helpful, but we don't have any plans for metric compatibility. The fonts are still far from stable, and it's too early to consider metric stability.
