### ISSUE TITLE
Review Noto LGC bugs and see if they also apply to Roboto

### ISSUE THREAD

**Issue by roozbehp** [google/roboto#117]
@moyogo has reported a lot of very good bugs in Noto. We need to see if they also exist in Roboto, and file new bugs for them. His list of Noto bugs is at:
https://github.com/googlei18n/noto-fonts/issues/created_by/moyogo

/cc @xiangyexiao

**Comment by jamesgk** [comment]
Done. There were a couple of things I found that I wasn't sure were considered issues with Roboto:

1. Glyphs ꞴꞵꞶꞷ (U+A7B4 U+A7B5 U+A7B6 U+A7B7) are missing. These seem to be very rare in commonly used fonts, however, so I'm not sure if we want them in Roboto.
2. https://github.com/googlei18n/noto-fonts/issues/505 includes a note that Noto needs "a 'locl' feature for Marshallese (MAH) that produces the cedilla forms for the letters listed (ĢĶĻŅŖģķļņŗ) and for combining cedilla (U+0327)." I'm not sure if we want the same for Roboto.

**Comment by roozbehp** [comment]
We want the Marshallese forms. Please open a new Roboto bug for that.

As for A7B4 etc, these are characters encode in Unicode 8.0 that were not part of the original plans for Roboto. Please file a separate bug for all of the Unicode 8.0 ones. You can find them from http://www.unicode.org/Public/UCD/latest/ucd/DerivedAge.txt.

**Comment by jamesgk** [comment]
With those new issues filed, want to close this? Or keep it open in anticipation of more Noto bugs needing to be investigated?

**Comment by roozbehp** [comment]
If you've looked at everything, let's close it.

**Comment by jamesgk** [comment]
This was done again for issues posted through Dec 8th 2015
