### ISSUE TITLE
Right French quotation marks ( » ) is missing on the weight 300.

### ISSUE THREAD

**Issue by rpluvina** [google/roboto#143]
it's all in the title,
best,
Raphaël
<img width="755" alt="capture d ecran 2015-12-03 a 19 31 04" src="https://cloud.githubusercontent.com/assets/13452339/11655478/63421f26-9dae-11e5-8014-05a365ad7286.png">

**Comment by codeman38** [comment]
Where are you loading the font from? That looks like an older version; the current version has different designs for "R" and "k".

**Comment by rpluvina** [comment]
I was loading the font from http://typecast.com/preview/google/Roboto as I thought it was the last version, which isn't. And effectively I just downloaded the last one on my laptop, and all French quotation marks are back there.
