### ISSUE TITLE
Roboto fonts overriding some NotoColorEmoji on android

### ISSUE THREAD

**Issue by tetsuo55** [google/roboto#146]
In reference to this issue: https://github.com/Ranks/emojione/issues/177

With the default settings Roboto fonts currently override the following emoji from NotoColorEmoji:

‼️ Double Exclamation Mark http://emojipedia.org/double-exclamation-mark/
⁉️ Exclamation Question Mark http://emojipedia.org/exclamation-question-mark/
©️ Copyright Sign http://emojipedia.org/copyright-sign/
®️ Registered Sign http://emojipedia.org/registered-sign/
™️ Trade Mark Sign http://emojipedia.org/trade-mark-sign/

Please modifiy the fonts so android is able to show the the color emoji instead of these simple black and white ones

**Comment by roozbehp** [comment]
This is intentional, since these characters are defined by Unicode to have a text appearance by default. Please see the Emoji_Presenation property in http://www.unicode.org/Public/emoji/2.0/emoji-data.txt.
