### ISSUE TITLE
Some monotonic and polytonic letters hang too far to the left

### ISSUE THREAD

**Issue by jamesgk** [google/roboto#154]
The tonos in Upsilontonos (Ύ U+038E) extends left beyond x=0. It looks nice overhanging lowercase letters, but looks off in many other contexts. See:

![roboto](https://cloud.githubusercontent.com/assets/988758/13162824/5f75413e-d65c-11e5-9317-deccfb876c39.png)

Apparently Roboto v1 didn't have this issue (as much); it may be best to more closely resemble that version of the glyph.

**Comment by anthrotype** [comment]
Isn't it only at the beginning of a word, hence preceded by a space?

**Comment by jamesgk** [comment]
Oh, that's good to know. In that case only the clipping issue is really a problem.

**Comment by moyogo** [comment]
The issue also applies to monotonic Έ Ή Ί in bold weights or to polytonic Ὺ Ὑ Ὓ Ὕ etc. in most weights, but it’s bit more complicated than that.
They are only at the beginning of words assuming either the character sequences don’t have accented all-caps words or the glyphs displayed don’t show the accents in all-caps words.

**Comment by jamesgk** [comment]
OK, I'm starting to suspect this is just another bug in the tools. This change: https://github.com/google/roboto/commit/56ad4064e8eeff6c320952daef8767188ae7fa63#diff-c95f738dd7cf75477ba26d394b6dffc5L37 (specifically, moving the `alignComponentsToAnchors` call to after `g.move`) essentially caused accent offsets from rules in res/diacritics.txt to be ignored, thus the tonos is not moved as far right as it should be in the resulting glyph.

The issues Denis brings up may be solved by reverting some changes to diacritics.txt in https://github.com/google/roboto/commit/27c451f660a532561976bb78dd6bbb9eb9add141. But as usual, I have no idea why these changes were made in the first place.
