### ISSUE TITLE
Buggy caracters with Roboto 300 on Chrome

### ISSUE THREAD

**Issue by ligne13** [google/roboto#160]
On Chrome Mac (Version 46.0.2490.86 (64-bit)), the Roboto 300 shows weird caracters in my paragraph text :
![image](https://cloud.githubusercontent.com/assets/81624/13547086/abd1e636-e2c3-11e5-8190-09284191ad25.png)

This is not happening with Roboto 400 and more, and not happening either in Firefox and Safari.

**Comment by fitojb** [comment]
You don’t have the latest version of Roboto installed. Please download the fonts again, from this repository.

**Comment by ligne13** [comment]
thanks
