### ISSUE TITLE
Shapes of Insular T may need improvement

### ISSUE THREAD

**Issue by roozbehp** [google/roboto#17]
Christian,

I think the shapes of Insular T are still problematic. What do you think? I'm including sample words from the Unicode proposal at http://www.unicode.org/L2/L2006/06266-n3122-insular.pdf.

Roboto Thin:
![roboto-100](https://cloud.githubusercontent.com/assets/302255/7310080/13f9de4a-e9db-11e4-9bdc-62af5e019304.png)

Segoe UI:
![segoeui](https://cloud.githubusercontent.com/assets/302255/7310086/2f2b3baa-e9db-11e4-8f85-4f0ff3d1ab52.png)

Roboto Regular:
![roboto-400](https://cloud.githubusercontent.com/assets/302255/7310083/220cc56a-e9db-11e4-979b-ae765011acfa.png)

Roboto Black:
![roboto-900](https://cloud.githubusercontent.com/assets/302255/7310088/37d22da4-e9db-11e4-9f6f-8f43ab5b68b0.png)

**Comment by xiangyexiao** [comment]
assign it to myself to contact the contractor and see if they can fix this.

**Comment by xiangyexiao** [comment]
It seems this issue has been fixed. See the current shape.
<img width="185" alt="screen shot 2015-08-03 at 2 59 44 pm" src="https://cloud.githubusercontent.com/assets/12721521/9048737/4fd32312-39f0-11e5-80c4-68d3ef882d4b.png">
