### ISSUE TITLE
Missing RobotoCondensed-Medium

### ISSUE THREAD

**Issue by antpaw** [google/roboto#172]
Hey, is there a way you could include RobotoCondensed-Medium into the project? Thanks

**Comment by jamesgk** [comment]
You can add instances yourself by editing scripts/build-v2.py and running the tools! Here's something I quickly came up with my adding the following (somewhere after `bdcnq` is assigned and the last call to `proj.generateTTFs()` is called):

```
proj.generateFont(Mix([cn1, bdcn1], 0.35),
                  "%s Condensed/Medium/Regular/Lt"%FAMILYNAME,
                  swapSuffixes=[".cn"])
```

0.35 interpolation may not be the best parameter, however. I don't think we have any plans to add a proper target for this ourselves.

[RobotoCondensed-Medium.zip](https://github.com/google/roboto/files/196070/RobotoCondensed-Medium.zip)

**Comment by antpaw** [comment]
thank you
