### ISSUE TITLE
rendering in Firefox

### ISSUE THREAD

**Issue by nameanyone** [google/roboto#174]
Don't know if it's an issue with Firefox or Roboto, but both releases from here render like below. Only in Firefox, and only Roboto from this repo. Google Fonts version is fine, Chrome is fine with either. Didn't check on Linux yet, I'm on Windows at the moment.

![2016-04-04_12-16-44](https://cloud.githubusercontent.com/assets/212368/14263519/e3179366-fa6f-11e5-8749-dbb79c341b0c.png)

**Comment by jamesgk** [comment]
I think this is an issue with all unhinted Roboto fonts. The "fix" would be to use the fonts in hinted/, and I'm planning on including updated hinted fonts in the next release.

A couple of notes:
- From my testing it seems that this affects Windows 7 but not 8.1, on IE as well as Firefox
- It's also an issue with the old unhinted fonts at https://github.com/google/roboto/tree/773e4c090fe012ecf0b09bbafc7e5926d4f86648/out

**Comment by jamesgk** [comment]
Latest release contains updated hinted fonts.
