### ISSUE TITLE
Add crunch and android TTF files to release

### ISSUE THREAD

**Issue by iwsfutcmd** [google/roboto#178]
I was talking to Roozbeh at the UTC meeting today about my difficulties building the TTF files from source, and he recommended filing an issue requesting adding the built files to a release. I see that 'roboto-unhinted' is available in the releases (which I assume to be the results of "make v2") but the results of "make crunch" and "make android" are not present - can they be added to a release, to allow users to avoid a lengthy and complicated build process if they wish to use the latest versions of Roboto on their devices?

**Comment by jamesgk** [comment]
Done. Thanks

**Comment by jamesgk** [comment]
Ah, did you actually want the output from "make crunch" as well? Not sure if it's useful but if you think so let me know and I can add it in.
