### ISSUE TITLE
Greek: Lowercase chi should probably be differentiated from lowercase Latin x

### ISSUE THREAD

**Issue by roozbehp** [google/roboto#18]
From internal bug 18782818:

@raphlinus:
> [...] I researched the shape of "χ" in a number of other contemporary Greek fonts, and see that the
> version without descenders is quite common. For example, it appears in the Ubuntu font, which was
> developed by a highly respected type foundry. In addition, in the discussion of
> http://typophile.com/node/29711 it is stated, "chi's and eta's without descenders are something that
> more and more appears in contemporary Greek typefaces (a big percentage of typefaces designed
> and used inside Greece)".
>
> It's a bit controversial. In http://blog.gmane.org/gmane.comp.fonts.dejavu/month=20061201 Ben
> Laenen states: "That is one of the concerns I'm having, and also that the Greek should be useable for
> ancient Greek as well. Therefor I'm still not too keen on the eta and chi without descenders." [...]

@roozbehp:
> This appears to be a deliberate change by Christian in Roboto 2 (Roboto 1 has a different chi than x).
>
> I personally don't like it: Roboto is now a default font everywhere, and Greek is not limited to modern
> Greek (there are lots of people using chi on the web for basic math, and they are now seeing their x's
> and their chis the same way [...]). Basically, I think we want to be more conservative
> with a system font.
>
> I also compared with the Windows 10 sans system fonts. Arial, Calibri, Segoe UI, and Tahoma, all
> differentiate their chis and their x's, I believe for similar reasons.
>
> [...] I think it needs to be fixed in Roboto 3.

@christianrobertson:
> Valid feedback. We should do more research on this question. Generally I
> agree with the point that we should choose the more conservative route for
> the system font, though in this case the answer isn't 100% clear. The math
> point is interesting since there are other characters where the expected
> math version of the symbol doesn't work well for running text, or has
> diverged from the common usage. In some cases there are multiple code
> points, but as far as I know it's not the case for chi.

Feedback from native Greek Googler:
> Just wanted to add in this discussion the fact that we (native Greeks) use
> 'x' as a multiplication symbol, which is another reason that if things stay
> as is there will be some major complications. ''x" is never used in Greek
> either as the English x character or the multiplication symbol.
>
> In schools, we are taught to write chi as chi and ita as 'η' but *without*
> the longtail. 'η' is actually considered an older form, no one is writing
> it like that at the moment (I should perhaps file another bug for this),
> but that seems to be more innocent than using a character from another
> language (x instead of chi). [...]

**Comment by roozbehp** [comment]
Also reported at https://code.google.com/p/android/issues/detail?id=160613. Quote:

> Quite apart from issues of correctness for Greek (I have no opinion on that since I don't know the language), some applications critically depend on them being distinguishable, for example the International Phonetic Alphabet. These letters represent respectively "voiceless velar fricative" and "voiceless uvular fricative".

**Comment by roozbehp** [comment]
From correspondence with Pieter Lamers ```<pieter.lamers@benjamins.nl>```:
> I came across your post on Github about the Roboto chi glyph, after it proved to be a show-stopper for use in academic publishing (in the case for showing statistical chi-square values). Would you know if anything is being done with your issue? If not we will start looking for another font.

**Comment by jamesgk** [comment]
As it turns out, the desired alternate chi glyph is already present in the sources (as "chi.alt"). So this should be an easy fix.
