### ISSUE TITLE
Inside of "e" is slanted 

### ISSUE THREAD

**Issue by seanfrasure** [google/roboto#180]
Got this on mobile:
![img_20160518_131844](https://cloud.githubusercontent.com/assets/9723817/15368305/20241c5e-1cfb-11e6-8ed1-4cf3b29f1ee2.JPG)
Its only with lowercase ...

**Comment by jamesgk** [comment]
Yikes. Can you provide more details as to where you saw this? Any particular app / device / Android version? I can't reproduce myself.

**Comment by seanfrasure** [comment]
Android Version: Android 4.2.2
App: Google Chrome

**Comment by jamesgk** [comment]
Duplicate of https://github.com/google/roboto/issues/181
