### ISSUE TITLE
Interior of "M" doesn't look right 

### ISSUE THREAD

**Issue by seanfrasure** [google/roboto#181]
Yet again... mobile 
![img_20160518_132610](https://cloud.githubusercontent.com/assets/9723817/15368602/a3abdc5a-1cfc-11e6-80b4-c427376d0fd2.JPG)

**Comment by seanfrasure** [comment]
Android Version: 4.2.2
App: Google Chrome

**Comment by fitojb** [comment]
Is this screenshot depicting a web page or the application’s UI? I suspect the former, since this image looks like fake bold, which is fixable by adding more weights to your web page.

**Comment by seanfrasure** [comment]
The screenshot is zoomed in from a web page. It is bold and I only use the default HTML <b> tag and not other styles/weights.

**Comment by fitojb** [comment]
Then the maintainer of that page should add a call to the bold weight of Roboto; otherwise you’ll keep seeing this fake (synthetic) bold.

Not a font bug.

**Comment by jamesgk** [comment]
Ahh, good call @fitojb. This is definitely not a rendering of the actual Roboto-Bold font.
