### ISSUE TITLE
Bug with "rt" letters and break-word (on desktop Chrome)

### ISSUE THREAD

**Issue by lepta-ua** [google/roboto#184]
Problem with lowercase "rt" letters combinations.

Watch details on stackoverflow - http://stackoverflow.com/questions/37512815/bug-with-roboto-font-and-break-word-on-desktop-chrome

**Comment by jamesgk** [comment]
I don't think this is a font bug. It seems that the browser is calculating the width of the enclosing box before applying kerning, then when the r and t are pushed apart the text wraps because the line has gotten longer.
