### ISSUE TITLE
Roboto on Chromium with Ubuntu 14.04 LTS -- Normal Weight Font Shown Bold

### ISSUE THREAD

**Issue by volomike** [google/roboto#194]
There's a Roboto font bug when viewing Roboto regular font, normal weight (400) on Chromium with Ubuntu 14.04 LTS. (Version of Chromium is listed as 50.0.2661.102.) It displays the font as bold instead of normal. This does not occur on Windows or MacOS. (Note, not that it might even matter, but I'm using Ubuntu 14.04 inside a Virtualbox VM on MacOS.)

**Comment by davelab6** [comment]
Please try uninstalling

**Comment by volomike** [comment]
I guess I don't understand? It's downloaded live in a web page, not installed.

**Comment by volomike** [comment]
Note that the problem doesn't occur on Firefox with Ubuntu 14.04. Just Chromium and Google Chrome.

**Comment by davelab6** [comment]
Chrome has a bug where if the don't is installed it does this

**Comment by volomike** [comment]
I finally got a moment to delete my old ~/.config/chromium profile, and then did "apt-get --purge remove chromium-*", and then did apt-get update; apt-get install chromium-browser. At that point, I went back to the Roboto font page on Google Fonts. Unfortunately, the problem still exists on Ubuntu Linux 14.04 with Chromium browser.

**Comment by davelab6** [comment]
Sorry my phone keyboard mangled my reply; its not Chromium to uninstall but the fonts, which may be in `~/.fonts` or `/usr/share/` somewhere

**Comment by volomike** [comment]
Thanks. That fixed me. I had to remove the Roboto font as a system font because for some reason it interferes when viewing in a web page. On Ubuntu 14.04, the fonts folder path is: ~/.local/share/fonts. I did rm Roboto-* inside that folder, closed my browser, reopened it, went to Google Web Fonts, and the problem was resolved.

**Comment by jungshik** [comment]
There are multiple points of failures: 1. fontconfig on Ubutun 14.04    2. Chrome (old version) not being able to deal with more than 2 weights. I believe 51 is fine (you're using 50.x), but it may have to be 52 (I have to check the changelog).

Anyway, this is not a Roboto font bug and should be closed.
