### ISSUE TITLE
Webfont fallbacks on missing glyphs in Roboto 400 doesn't work properly in OSX Chrome

### ISSUE THREAD

**Issue by diagramatics** [google/roboto#200]
Not sure if this is the right place to report webfont related issues but I'll give this a shot. Apologies if this is the wrong place as I'm really stumped about where to report this issue to.

We are using Roboto in our site at the moment and noticed that Roboto 400 doesn't display the fallback font if the glyphs used with Roboto is missing. For example, loading Roboto with `font-family: Roboto, sans-serif` CSS on a Japanese text will display a lot of missing glyphs characters instead of the text in `sans-serif`. This behaviour happens to me on a Mac OS X 10.11.5 running Chrome and Chrome Canary. Other browsers don't exhibit this behaviour weirdly enough.

YouTube, which is using Roboto as you may have known, has problems displaying Japanese words in Roboto 400 as well.

![image](https://cloud.githubusercontent.com/assets/5153378/17213778/2a72d47e-5519-11e6-80f7-d32fb83cc56c.png)

You can see that the description is all replaced with missing glyphs and the headings on the suggested videos on the right using Roboto 500 is not affected.

![perf2](https://cloud.githubusercontent.com/assets/5153378/17213806/59c6ef8a-5519-11e6-8506-d39218d56d4d.gif)

Same goes with Google Fonts, which is using Roboto 400 for their input to ask for words to type to view the same text in the font you choose.

**Comment by davelab6** [comment]
Are you using the web font via the google fonts api or self hosting?

Github.com/google/fonts/issues might be better for this

**Comment by diagramatics** [comment]
In this bug's case, both. We self-hosted it but I skimmed over YouTube and Google Fonts and they both are using Google Fonts.

**Comment by diagramatics** [comment]
Just found out that the issue belongs to Typekit. I installed Roboto 400, 400 italic, 700 and 700 italic over at Typekit and it seems like the way Typekit handles it produces issues on the font stack. This is what Chrome tells me:

![image](https://cloud.githubusercontent.com/assets/5153378/17276972/efca33e4-577a-11e6-8daf-640f5a5455b0.png)

Anyway closing this issue since it's a Typekit/Adobe issue or Chrome's.

**Comment by adong** [comment]
This happened to me, and I think its Chrome's issue.
