### ISSUE TITLE
Wrong language system tag for Turkish

### ISSUE THREAD

**Issue by brawer** [google/roboto#203]
The `GSUB` and `GPOS` tables of Roboto have special lookups for language `TUR`. However, this is actually not a registered [OpenType language system tag](https://www.microsoft.com/typography/otspec/languagetags.htm). To enable lookups for the Turkish language, Roboto should use the language system tag `TRK` instead of `TUR`. (The other tags are fine, only `TUR` is undefined).

``` sh
$ ttx -t GSUB -t GPOS  -o - ~/Downloads/Roboto-Regular.ttf | grep LangSysTag | sort -u
            <LangSysTag value="AZE "/>
            <LangSysTag value="CRT "/>
            <LangSysTag value="FRA "/>
            <LangSysTag value="MOL "/>
            <LangSysTag value="NAV "/>
            <LangSysTag value="ROM "/>
            <LangSysTag value="TUR "/>
```

**Comment by brawer** [comment]
I’ve used this file: https://github.com/google/roboto/blob/master/hinted/Roboto-Regular.ttf

**Comment by adrientetar** [comment]
This was fixed in #193, I believe.

**Comment by jamesgk** [comment]
Yea, the fonts in `hinted/` contain bugs which are fixed by post-production scripts. The fonts in the latest release should be correct.

**Comment by davelab6** [comment]
@jamesgk can this be closed?

**Comment by jamesgk** [comment]
Yep, thanks.
