### ISSUE TITLE
Text combination of AE is being rendered as Æ in font-weight:400

### ISSUE THREAD

**Issue by monstanl** [google/roboto#208]
Strange behaivor of the text combination AE being renderd as Æ. This only happens when the font-weight is set on Roboto 400. This letter combination finds its origin as the letter of the Old English (Anglo-Saxon) alphabet. This also happends when the letters are lowercase.

**Comment by jamesgk** [comment]
I'm unable to reproduce, could you provide more details as to where you saw this?

**Comment by monstanl** [comment]
It turned out I was using an older version installed on my local machine, after installing the set the problem was gone.
