### ISSUE TITLE
Font Weight

### ISSUE THREAD

**Issue by Blackglade** [google/roboto#210]
So I've noticed a bug and through a bit of research I'm not exactly sure if it's the browsers (Edge, Chrome, Safari) doing this or the font itself. Importing the Roboto Font (100, 300, 400, 500, 700, 900). The font weights of 700 and 900 look exactly the same and there is no change. While going from 500 to 600 and 600 to 700 there is a change despite Roboto not being offered under the 600 weight. I must be going crazy here, but what's going on and how do I fix this?

**Comment by davelab6** [comment]
Try uninstalling the fonts

**Comment by Blackglade** [comment]
Okay so I definitely noticed a difference when I uninstalled the fonts, but now different weights such as 100 and 300 are showing up as the same (around 400 weight). Despite me only importing only 100, 300 and 700?
