### ISSUE TITLE
FontAgentPro strangely replacing certain characters?

### ISSUE THREAD

**Issue by volcanicc** [google/roboto#211]
Firstly, thanks for the beautiful font :^)

Just noticed OSX just does some strange things to it especially when loading via Font Agent Pro.

I even re-downloaded the google-font to be safe deleting all previous versions, yet the issue is still there. FontAgent pro is somehow rendering a very similar but different font.

Attached screenshots of Google Font looking great, then screen shot of Fontbook preview showing the active set note especially the "R". Finally screenshot of FontBook showing all ok.
<img width="954" alt="osx-google-font-browser-preview" src="https://cloud.githubusercontent.com/assets/8055666/20035038/3f06f31c-a428-11e6-809d-4c69ebb00a1a.png">
<img width="785" alt="osx-fontagebntpro-incorrect" src="https://cloud.githubusercontent.com/assets/8055666/20035041/43c200a4-a428-11e6-8c7e-066fb609afec.png">
<img width="578" alt="osx-fontbook" src="https://cloud.githubusercontent.com/assets/8055666/20035043/457fbd14-a428-11e6-8637-cbcef2beef1c.png">

Only workaround is to load in OSX native FontBook app, seems to be fine from there.

Is it perhaps just a FontAgent glitch or have there been any known clashes with perhaps previously loaded fonts?

**Comment by fitojb** [comment]
Yes, judging from your screenshots it looks like your installation of FontAgent Pro is loading a very old version of Roboto (pre-Material Design), and that’s why you’re seeing design differences. Could it be that there is a cache that needs to be flushed?, given you said that you’ve removed all previous versions of Roboto from your machine…

Anyways, this seems to be a ticket best suited for a FontAgent support forum and not this repository.

**Comment by volcanicc** [comment]
Thanks, fair call, I'll log it with FontAgent.

Feel free to delete this thread, cheers :^)
