### ISSUE TITLE
Kerning for P+comma+quote is overly tight

### ISSUE THREAD

**Issue by codeman38** [google/roboto#213]
In recent versions of Roboto (at least 2.132 through 2.135), the kerning of `P,` and `,'` are tight enough that, in the string `P,'`, the quotation mark actually overlaps with the letter P. This is the case with all comma-quote kerning pairs (single and double quotes, straight and curly).

<img width="289" alt="screen shot 2016-12-04 at 1 02 17 pm" src="https://cloud.githubusercontent.com/assets/386563/20868136/f242b768-ba21-11e6-9d7b-c075027ffb63.png">

**Comment by fitojb** [comment]
Looks related to issue #195

**Comment by jamesgk** [comment]
Yikes, I think I introduced this with https://github.com/google/roboto/commit/ecbda8dcfab710d96a16f1b0d7aac1ecfd6d6267 (but not the `L'` issue which has always been in v2). I guess the old behavior, which didn't actually interpolate kerning rules, actually worked better as a kind of happy accident. Thanks for the catch.

**Comment by ron23** [comment]
I think I'm seeing a related behavior:
![image](https://user-images.githubusercontent.com/5150512/27366428-eb86d556-55fa-11e7-8e14-5d882bcb09aa.png)

**Comment by jamesgk** [comment]
It looks like you're using Roboto version 1 (from the square colon). The
kerning in version 2 between "P:" should be fine.
