### ISSUE TITLE
The Roboto Slab variant is missing

### ISSUE THREAD

**Issue by legovini** [google/roboto#216]
The serif variant Roboto Slab is not included in this repository. Several Linux distributions use this repository to package the Roboto font, and thus miss Roboto Slab. As an example see this Debian bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819273

Please add Roboto Slab.

Thank you,
Paride

**Comment by roozbehp** [comment]
We have no plans to include Roboto Slab in this repository. You can get it from https://github.com/google/fonts/tree/master/apache/robotoslab.
