### ISSUE TITLE
No loca feature for Macedonian and Serbian Cyrilic in Roboto Italic

### ISSUE THREAD

**Issue by marekjez86** [google/roboto#224]
Current handling of Macedonian and Serbian Cyrilic by Roboto Italic:
![mksr](https://cloud.githubusercontent.com/assets/13322623/21554165/131af960-cdc2-11e6-9e7a-b13b3fc09021.jpeg)

The text above was created by https://github.com/googlei18n/fontdiff using
```html
<html>
	<p lang="mk" style="font-weight:700">Macedonian 0413 г 0414 д 041F п 0422 т 0403 ѓ</p>
	<p lang="sr" style="font-weight:700">Serbian 0413 г 0414 д 041F п 0422 т 0403 ѓ</p>
</html>
```
as input.

I copied the text below which was created by https://github.com/elTooDR in https://github.com/googlei18n/noto-fonts/issues/794 (it pertains to Macedonian but it also applies to Serbian).

Also please note that if you sequence Macedonian (or Serbian) Unicode 0422 then 041F then 0413 they all should be "visually compatible" (but listed from the longest to the shortest). [I'm not a designer sorry for a convoluted description.] For example,
Noto Sans Italic
![notosans-italic](https://cloud.githubusercontent.com/assets/13322623/21554815/a3ddaf10-cdc7-11e6-84a7-00796394b92f.jpeg)
Noto Serif Italic
![notoserif-italic](https://cloud.githubusercontent.com/assets/13322623/21554809/9e314ea0-cdc7-11e6-9206-948d0191d377.jpeg)

**\<beginning of copied text\>**"
Macedonian needs a local/vernacular version for a number of lower case characters when italicized. These are mentioned below.

Unicode 0413 - Г г _г_ - IPA /g/ - English equivalent g
Regular   |   Incorrect Italics    |   Correct Italics
![g](https://cloud.githubusercontent.com/assets/23340932/21140127/b4ea24b6-c136-11e6-9a24-e0121827ea9b.JPG)
The correct lower case g does not have a curve on the vertical stroke and it also has macron over it. The correct character would be similar to iota in Greek “ι” as opposed to a mirrored “s, s”. 

Unicode 0403 - Ѓ ѓ _ѓ_ - IPA /ɟ/ - English equivalent gy
Regular   |   Incorrect Italics    |   Correct Italics
![gj](https://cloud.githubusercontent.com/assets/23340932/21140356/e9d5fa00-c137-11e6-955b-8f51de646a2d.JPG)
As above, except with an acute diacritic above the macron. 

Unicode 0414 - Д д _д_ - IPA /d/ - English equivalent d
Regular   |   Incorrect Italics    |   Correct Italics
![image](https://cloud.githubusercontent.com/assets/23340932/21140424/4186ebec-c138-11e6-892d-9597fbac1d8f.png)
The lower case d in Macedonian should have the tail pointing down. It is similar to italicized g in English.

Unicode 041F - П п _п_ - IPA /p/ - English equivalent p
Regular   |   Incorrect Italics    |   Correct Italics
![image](https://cloud.githubusercontent.com/assets/23340932/21140499/a35a8c84-c138-11e6-9cf2-3cf085aabf6c.png)
The lower case p in Macedonian should look like a u with a macron over it. Currently, it seems to be very similar to n in English.

Unicode 0422 - Т т _т_ - IPA /t/ - English equivalent t
![image](https://cloud.githubusercontent.com/assets/23340932/21140550/f61087d0-c138-11e6-93f9-eea283223e45.png)
The lower case t in Macedonian should look like the character “sh” Unicode: 0428 ш with a macron over it. Currently, it seems to be very similar to m in English. 

I hope everything is clear. 

The Macedonian Ministry of Information Society (MIO) released a number of fonts (Skola) to the general public which may help - http://www.mio.gov.mk/?q=node/2182. Click on Преземи ги фонтовите to download the fonts.
"**\<end of copied text\>**

**Comment by marekjez86** [comment]
I haven't checked Roboto Slab nor Roboto Condensed but I suspect they suffer from the same issue (if they have italics).

**Comment by elTooDR** [comment]
@marekjez86 This font in italics is simply slanted to the right. This is a similar situation to Verdana. Because of this the characters are already displayed correctly for Macedonian. I also think Serbian displays as well but I am not sure.

**Comment by StefanPeev** [comment]
@marekjez86 I've a question. Is there Adobe software (for example Indesign) or even other software for working with texts, which is able to localise Serbian and Macedonian as a preferred working languages? The question is important, because if there isn't a software which is able to localize these two languages, than the only one way to two add Serbian and Macedonian glyph forms is through Style Set options. I personally prefer in the Open Type fonts to put both – loclBGR, loclSRB, loclMCD and Style Set options which duplicate this localisation.

**Comment by roozbehp** [comment]
Roboto Italic is not a true Italic font, just a slanted font. So it's not appropriate for it to have localized forms for Serbian and Macedonian.
