### ISSUE TITLE
enhancement: ᴕᴽ U+1D15 U+1D3D should be based on Ȣ U+0222 instead of having a different top counter.

### ISSUE THREAD

**Issue by marekjez86** [google/roboto#225]
This is an enhancement request

test case
```html
<html lang="en-phonipa">
<p><span style="font-size:36.0px">Ȣȣᴕᴽ</span></p>
</html>
```

using fontdiff on font (against itself) yields
![u 0222](https://cloud.githubusercontent.com/assets/13322623/21593803/fdbf78e6-d0cf-11e6-8104-223cfb4d93ea.jpeg)

ᴕᴽ U+1D15 U+1D3D should be based on Ȣ U+0222 instead of having a different top counter.

**Comment by jamesgk** [comment]
I opened a bug for this a while back: https://github.com/google/roboto/issues/124

**Comment by marekjez86** [comment]
MTI Note: "Align anoteleia with colon dot. To add a style variant for all cap or small cap settings is TBD"
