### ISSUE TITLE
Roboto not able to render chinese characters

### ISSUE THREAD

**Issue by Zaithe** [google/roboto#228]
When using google search, the default font is Roboto which i cannot change. This font is unable to render chinese characters which is a big issue. 

![screen shot 2017-01-10 at 1 47 43 pm](https://cloud.githubusercontent.com/assets/2839791/21826224/847f5f24-d73b-11e6-8dcf-3b120c1b5777.png)

**Comment by roozbehp** [comment]
Roboto is limited to Latin, Greek, and Cyrillic. Please go to the Noto project for Chinese fonts.

**Comment by raffaelmeier** [comment]
The Noto Project Website does only provide fonts in ttf. for the eot woff etc. I had to generate my own files and made use of https://transfonter.org/ - this was a quite easy way and worked at once. I was seeking quite a couple of minutes with not much success for woff and eot sources...
