### ISSUE TITLE
Roboto Hinted v2.136 vs hinted v2.000: Have the cvt values changed?

### ISSUE THREAD

**Issue by m4rc1e** [google/roboto#236]
We'd like to update the Roboto fonts being served on Google Fonts.

Google Fonts is currently serving the hinted v2.000 binaries. We're hoping to replace it with the hinted [v2.136](https://github.com/google/roboto/releases) binaries.

I've noticed a few x-height/cap height jumps when viewing the fonts on Windows. I'm curious if the cvt values were changed in the hinted sources? 

![roboto-hinting-win](https://cloud.githubusercontent.com/assets/7525512/23711745/a476bef8-0418-11e7-8737-e24351d80ac8.gif)
*Win 7 Chrome v56: 8pt x-height jumps a pixel*

I tried locating the hinted sources but all I found were binaries with hints already compiled.

Unfortunately, some GF users are very sensitive to such subtle changes, https://github.com/google/fonts/issues/528, https://github.com/Semantic-Org/Semantic-UI/issues/4998. They base their whole interface on pixel precision. This 1px raise in x-height usually destroys their nav bars or buttons.

Sorry if this sounds petty, we've been burned many times.

cc @davelab6

**Comment by davelab6** [comment]
> I tried locating the hinted sources but all I found were binaries with hints already compiled.

That's right, there are no sources available for the hinting; it was done by a vendor. I'll ask for clarification of this issue :)

**Comment by davelab6** [comment]
Closing as GF will push this update without further changes to the CVT table.
