### ISSUE TITLE
Last Support Date for Current Release of Google Roboto Font

### ISSUE THREAD

**Issue by davezen1** [google/roboto#240]
What is the support time for a given release?  Does support for a given font release end when a new release is created such as v2.136?

**Comment by davelab6** [comment]
What do you mean by 'support' exactly? :)

**Comment by davezen1** [comment]
I know it is a font but how are issues handled? If there is an issue discovered and fixed in a major, minor, or patch release would that mean only the latest release would have the fix? I mean to use support in the context of ensuring I am using the latest stable version.

I am using a script to download fonts pointing to a url for use in a library that looks like:

https://fonts.googleapis.com/css?family=Roboto:300,300italic,400,400italic,500,500italic,700,700italic&subset=latin,greek,greek-ext,latin-ext,cyrillic-ext,cyrillic

In that there are links with references to v15:

https://fonts.gstatic.com/s/roboto/v15/-L14Jk06m6pUHB-5mXQQnYX0hVgzZQUfRDuZrPvH3D8.woff2

So, I want to understand how the versions get updated as it was not completely clear from what I have read.

**Comment by m4rc1e** [comment]
@davezen1 The bug fixes get applied to the latest release only.

**Comment by davelab6** [comment]
Thanks for clarifying! 

> What is the support time for a given release? Does support for a given font release end when a new release is created

Yes, there is no support time for a given release; only the current release is supported. 

> such as v2.136?

No, the versions in the upstream repos and recorded inside the font files own metadata, like v2.136, are not related in any way to the versions that you can observe if you look inside the Google Fonts CSS API. 

> I know it is a font but how are issues handled? If there is an issue discovered and fixed in a major, minor, or patch release would that mean only the latest release would have the fix? I mean to use support in the context of ensuring I am using the latest stable version.

The OpenType font format version metadata only supports major/minor numbers, not patch release numbers; and there are no established conventions about how to increment these numbers in the font developer community. 

> I am using a script to download fonts pointing to a url for use in a library that looks like:
>
> https://fonts.googleapis.com/css?family=Roboto:300,300italic,400,400italic,500,500italic,700,700italic&subset=latin,greek,greek-ext,latin-ext,cyrillic-ext,cyrillic
>
> In that there are links with references to v15:
>
> https://fonts.gstatic.com/s/roboto/v15/-L14Jk06m6pUHB-5mXQQnYX0hVgzZQUfRDuZrPvH3D8.woff2
>
> So, I want to understand how the versions get updated as it was not completely clear from what I have read.

The versions in the URLs of the fonts are "private" to the API, and not supported. Do not use them. If you do, expect the URLs to disappear without warning. 

Instead, use the CSS API, which is not versioned and always returns the latest release.
