### ISSUE TITLE
Issue with word in thai

### ISSUE THREAD

**Issue by hendrysadrak** [google/roboto#242]
Issue with rendering word ไพ่คู่ั่งผู้เล่น

Using latest version of Roboto (v2.136). Environment is web, fonts not converted, using original .ttf's

Received: 
![image](https://cloud.githubusercontent.com/assets/4000963/24861174/65cc8af0-1e00-11e7-9daa-502802ec48ef.png)

Expected something like:
![image](https://cloud.githubusercontent.com/assets/4000963/24861221/9c1955e8-1e00-11e7-9e2a-d5903f0abbac.png)

So my question is, if there will be support for this or should i change the fonts?

**Comment by davelab6** [comment]
Roboto doesn't support Thai, so what you are seeing is not Roboto but another font.
