### ISSUE TITLE
How to download the font Roboto v15?

### ISSUE THREAD

**Issue by Wladkh** [google/roboto#245]
For downloading, I always used this link: "https://fonts.googleapis.com/css?family=Roboto:400,900&subset=latin,cyrillic", but for several days I've noticed that the Roboto 16/18/20px font has become more elongated. I look in the css file, and there appears a new version of "s/roboto/v16/".

The font began to resemble Arial. I use an adaptive design and when changing the font size, the design of the site changes greatly.

The question is, сan I somehow specify forcibly that I need the 15 version?
For example, https://fonts.googleapis.com/css?family=Roboto:400,900&v=15 ?

**Comment by m4rc1e** [comment]
You can get the old versions from the google/fonts.

The decovar branch was created before the Roboto v2.136/2.137 pr was made:
https://github.com/google/fonts/tree/decovar/apache/roboto

**Comment by Wladkh** [comment]
**m4rc1e,** Please tell me https://fonts.googleapis.com/css?family=Roboto:400,900 for different browsers gives different content. Does this affect the display in different browsers and OS? That is, under a specific browser, the most correctly rendered font?

Can I use this file and replace version 16 with 15  ("s/roboto/v16" "s/roboto/v15")? That is, I place this file on my server and refer to it (<link href="https://mysite/myfont/css" rel="stylesheet" type="text/css">)?

> /* cyrillic-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v16/ek4gzZ-GeXAPcSbHtCeQI_esZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
}
/* cyrillic */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v16/mErvLBYg_cXG3rLvUsKT_fesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* greek-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v16/-2n2p-_Y08sg57CNWQfKNvesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+1F00-1FFF;
}
/* greek */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v16/u0TOpm082MNkS5K0Q4rhqvesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0370-03FF;
}
/* vietnamese */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v16/NdF9MtnOpLzo-noMoG0miPesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0102-0103, U+1EA0-1EF9, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v16/Fcx7Wwv8OzT71A3E1XOAjvesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
}
/* cyrillic-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 900;
  src: local('Roboto Black'), local('Roboto-Black'), url(https://fonts.gstatic.com/s/roboto/v16/s7gftie1JANC-QmDJvMWZhJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
}
/* cyrillic */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 900;
  src: local('Roboto Black'), local('Roboto-Black'), url(https://fonts.gstatic.com/s/roboto/v16/3Y_xCyt7TNunMGg0Et2pnhJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* greek-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 900;
  src: local('Roboto Black'), local('Roboto-Black'), url(https://fonts.gstatic.com/s/roboto/v16/WeQRRE07FDkIrr29oHQgHBJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+1F00-1FFF;
}
/* greek */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 900;
  src: local('Roboto Black'), local('Roboto-Black'), url(https://fonts.gstatic.com/s/roboto/v16/jyIYROCkJM3gZ4KV00YXOBJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0370-03FF;
}
/* vietnamese */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 900;
  src: local('Roboto Black'), local('Roboto-Black'), url(https://fonts.gstatic.com/s/roboto/v16/phsu-QZXz1JBv0PbFoPmEBJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0102-0103, U+1EA0-1EF9, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 900;
  src: local('Roboto Black'), local('Roboto-Black'), url(https://fonts.gstatic.com/s/roboto/v16/9_7S_tWeGDh5Pq3u05RVkhJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 900;
  src: local('Roboto Black'), local('Roboto-Black'), url(https://fonts.gstatic.com/s/roboto/v16/mnpfi9pxYH-Go5UiibESIltXRa8TVwTICgirnJhmVJw.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
}

Thank you!

**Comment by davelab6** [comment]
> For downloading, I always used this link: "https://fonts.googleapis.com/css?family=Roboto:400,900&subset=latin,cyrillic", but for several days I've noticed that the Roboto 16/18/20px font has become more elongated. I look in the css file, and there appears a new version of "s/roboto/v16/".

Right; the fonts were updating fixing many bugs, including some (longstanding) hinting bugs. 

> The font began to resemble Arial. I use an adaptive design and when changing the font size, the design of the site changes greatly.

The text layout should not have changed, only the apparent height of the letters on some OS at some sizes. 

> The question is, сan I somehow specify forcibly that I need the 15 version?
For example, https://fonts.googleapis.com/css?family=Roboto:400,900&v=15 ?

No. 

However, you can self-host the old (broken) version of the fonts, if you wish. 

> Please tell me https://fonts.googleapis.com/css?family=Roboto:400,900 for different browsers gives different content. Does this affect the display in different browsers and OS? That is, under a specific browser, the most correctly rendered font?

Yes, the CSS API parses the UserAgent string in each request and returns different font URLs for different UserAgents. 

> Can I use this file and replace version 16 with 15 ("s/roboto/v16" "s/roboto/v15")? That is, I place this file on my server and refer to it (<link href="https://mysite/myfont/css" rel="stylesheet" type="text/css">)?

No. Do not use font URLs directly, only use the CSS API. If you use font URLs directly, they may break without warning.

**Comment by Wladkh** [comment]
@davelab6 Why is it very sensitive? For example, I have a font size of articles on the site 17px, and the font size of the comments is 16px. Before that, everything looked harmonious. After the change, the text of the article looks normal, and the comments are stretched and very different from the article itself. Users complain that it became inconvenient to read. On Android everything is fine, but on Windows it's a real trouble ...

> The text layout should not have changed, only the apparent height of the letters on some OS at some sizes.
Is there a full list of OSes in which the font on even sizes (14/16/18p...) is stretched? 

I see two solutions: the first is to abandon Roboto and switch to a different font (I really do not want it, because the font is like it)
The second, I want to write a script that under this list the OS will replace in the received answer "https://fonts.googleapis.com/css?family=Roboto:400,900&subset=latin,cyrillic" roboto/v16 on roboto/v15. 
That is, in all lines of the css file, replace src. For example, src: local ('Roboto'), local ('Roboto-Regular'), url (https://fonts.gstatic.com/s/roboto/v16 replace with src: local ('Roboto'), local ( 'Roboto-Regular'), url (https://fonts.gstatic.com/s/roboto/v15
