### ISSUE TITLE
Redistribution and the Apache License Version 2.0

### ISSUE THREAD

**Issue by dev3456** [google/roboto#247]
Hello,

I was looking into self-hosting the Roboto font and using it with `@font-face` in a webpage.

While reading the [Apache License Version 2.0](https://github.com/google/roboto/blob/master/LICENSE), under the _"4. Redistribution."_ section, it says: _"(a) You must give any other recipients of the Work or Derivative Works a copy of this License; and"_.

I was wondering how to comply with that in a webpage? Does the webpage has to include the [LICENSE text](https://github.com/google/roboto/blob/master/LICENSE) on its source code?

**Comment by davelab6** [comment]
We can't offer legal advice on how to comply, I'm afraid. However, I note that all Roboto files have a URL for the Apache license inside. I see http://apache.org/foundation/license-faq.html doesn't cover this; I suggest trying http://www.apache.org/legal/

**Comment by dev3456** [comment]
I understand. Tyvm for the reply.

On a side note, are there any plans to change the Apache License Version 2.0 to the SIL Open Font License Version 1.1 [like it was done to the Noto font](https://github.com/googlei18n/noto-fonts/blob/master/NEWS)?

**Comment by davelab6** [comment]
Would that benefit you?

**Comment by dev3456** [comment]
I believe it would benefit everyone using the font on webpages with `@font-face` because it would solve the distribution problem under the [Apache License Version 2.0](https://github.com/google/roboto/blob/master/LICENSE).

The [SIL Open Font License Version 1.1](https://github.com/googlei18n/noto-fonts/blob/master/LICENSE) allows the copyright notice and the license to be added to the font's metadata:

> 2) Original or Modified Versions of the Font Software may be bundled, redistributed and/or sold with any software, provided that each copy contains the above copyright notice and this license. These can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields within text or binary files as long as those fields can be easily viewed by the user.

This way, all requirements for the font distribution could be packed on the font itself.

The same also applies to other Apache licensed fonts, like Droid.

**Comment by dev3456** [comment]
Sorry to bother again. But would it be possible to submit this suggestion to Google to evaluate?

**Comment by davelab6** [comment]
What do you see as the distribution problem?

**Comment by dev3456** [comment]
When we use a font with `@font-face` on a web page we're redistributing that font.

The [Apache License Version 2.0](https://github.com/google/roboto/blob/master/LICENSE) requires that on redistribution we must give a copy of the license.

> (a) You must give any other recipients of the Work or Derivative Works a copy of this License; and

Giving a copy of the license on a web page is the problem.

The Apache License wasn't designed for this kind of redistribution. It was meant for distributing software on which adding a `LICENSE.TXT` file to a folder would not be a problem. However, we can't just add a `LICENSE.TXT` to a web page.

Changing the license to the [SIL Open Font License Version 1.1](https://github.com/googlei18n/noto-fonts/blob/master/LICENSE) would solve all problems related to redistribution, since it allows the copyright notice and the license to be added to the font's metadata:

> Original or Modified Versions of the Font Software may be bundled, redistributed and/or sold with any software, provided that each copy contains the above copyright notice and this license. These can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields within text or binary files as long as those fields can be easily viewed by the user.

This way, all requirements for the font distribution could be packed on the font itself.

Furthermore, the [SIL Open Font License Version 1.1](https://github.com/googlei18n/noto-fonts/blob/master/LICENSE) was [designed considering that use case in mind](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#1b11b702):

> using @font-face to distribute the font directly to browsers. This is recommended and explicitly allowed by the licensing model because it is distribution. The font file itself is distributed with other components of the webpage. It is not embedded in the webpage but referenced through a web address which will cause the browser to retrieve and use the corresponding font to render the webpage (see 1.11 and 1.15 for details related to embedding fonts into documents). As you take advantage of the @font-face cross-platform standard, be aware that web fonts are often tuned for a web environment and not intended for installation and use outside a browser. The reasons in favour of using web fonts are to allow design of dynamic text elements instead of static graphics, to make it easier for content to be localized and translated, indexed and searched, and all this with cross-platform open standards without depending on restricted extensions or plugins. You should check the CSS cascade (the order in which fonts are being called or delivered to your users) when testing.

**Comment by dev3456** [comment]
If I may, I'd like to add that there's precedent for that change. [Google did it for the Noto font](https://github.com/googlei18n/noto-fonts/blob/master/NEWS):

> September 29, 2015
>
> All Noto fonts now licensed under Open Font License 1.1
>
> With the new release we have moved from Apache 2.0 to Open Font License 1.1 (OFL 1.1).  We are making this change because it makes it easier for you, the end users of Noto, to use the fonts that we produce.  When we first released the Noto fonts the OFL license was still a bit of an unknown entity and the Apache license looked familiar to us.  Over the years the OFL license has become the most commonly used and understood license to use for open source fonts.
>
> All of our fonts going forward from this release will be available only under the OFL license.  If you still want the fonts under the Apache license you can get them from the repo using the tag 'v2015-09-29-license-apache'.  However, new fonts and updates to existing fonts will use the OFL license.
