### ISSUE TITLE
Question: What about version 2.137?

### ISSUE THREAD

**Issue by NiklasBr** [google/roboto#248]
Just a small question: I noticed [google/fonts](https://github.com/google/fonts/pull/727) updated to version 2.137 a while ago, and so did [googlefonts/robototester](https://github.com/googlefonts/robototester). But the latest version in this repository is still v2.136. Is 2.137 available here (just not tagged as such) or will it be?

**Comment by m4rc1e** [comment]
@davelab6 We should probably tag a release for this.

Thanks @NiklasBr

**Comment by codeman38** [comment]
There's still no tag for 2.138 either, despite that having been merged a week ago.

**Comment by NiklasBr** [comment]
These tags would be nice.

**Comment by davelab6** [comment]
I've now tagged and released https://github.com/google/roboto/releases/tag/v2.138
