### ISSUE TITLE
U+2162 has incorrect horizontal advance

### ISSUE THREAD

**Issue by davelab6** [google/roboto#251]
Roboto-Regular.ttf before:
```xml
    <TTGlyph name="uni2162" xMin="183" yMin="0" xMax="1410" yMax="1456">
      <component glyphName="I" x="0" y="0" flags="0x4"/>
      <component glyphName="I" x="517" y="0" flags="0x4"/>
      <component glyphName="I" x="1034" y="0" flags="0x4"/>
    </TTGlyph>
```
Roboto-Regular.ttf now:
```xml
    <TTGlyph name="uni2162" xMin="183" yMin="0" xMax="1410" yMax="1456">
      <component glyphName="I" x="0" y="0" flags="0x204"/>  // The 9th bit is on
      <component glyphName="I" x="517" y="0" flags="0x4"/>
      <component glyphName="I" x="1034" y="0" flags="0x4"/>
    </TTGlyph>
```

**Comment by m4rc1e** [comment]
@davelab6 

v2.129 (first tagged [release](https://github.com/google/roboto/releases)) has the same issue.

```
    <TTGlyph name="uni2162" xMin="183" yMin="0" xMax="1410" yMax="1456">
      <component glyphName="I" x="0" y="0" flags="0x204"/>
      <component glyphName="I" x="517" y="0" flags="0x4"/>
      <component glyphName="I" x="1034" y="0" flags="0x4"/>
    </TTGlyph>

```
I need to know which versions they're testing?

According to the [spec](https://www.microsoft.com/typography/otspec/glyf.htm), when component flag bit 9, USE_MY_METRICS is enabled:

>If set, this forces the aw and lsb (and rsb) for the composite to be equal to those from this original glyph. This works for hinted and unhinted characters.

I need to dig deeper into this.

**Comment by davelab6** [comment]
If you use the character, you see the problem - negative advance width
compared to bounding box 😂

On May 23, 2017 5:05 AM, "Marc Foley" <notifications@github.com> wrote:

@davelab6 <https://github.com/davelab6>

v2.129 (first tagged release <https://github.com/google/roboto/releases>)
has the same issue.

    <TTGlyph name="uni2162" xMin="183" yMin="0" xMax="1410" yMax="1456">
      <component glyphName="I" x="0" y="0" flags="0x204"/>
      <component glyphName="I" x="517" y="0" flags="0x4"/>
      <component glyphName="I" x="1034" y="0" flags="0x4"/>
    </TTGlyph>


I need to know which versions they're testing?

According to the spec <https://www.microsoft.com/typography/otspec/glyf.htm>,
when component flag bit 9, USE_MY_METRICS is enabled:

If set, this forces the aw and lsb (and rsb) for the composite to be equal
to those from this original glyph. This works for hinted and unhinted
characters.

I need to dig deeper into this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/google/roboto/issues/251#issuecomment-303337352>, or mute
the thread

**Comment by m4rc1e** [comment]
@davelab6 the .ufo sources are fine. It's the tools which make it. Will have more info asap.
