### ISSUE TITLE
Missing import?  Where is Point() defined?

### ISSUE THREAD

**Issue by cclauss** [google/roboto#266]
The [transformGlyphMembers() function in Build.py](https://github.com/google/roboto/blob/ab4876f650a4aeb9b661c83fee47f908c739bb70/scripts/lib/fontbuild/Build.py#L187) creates Point() objects in four places but I am not able to find the definition of Point().  Is it some sort of builtn?

**Comment by davelab6** [comment]
Robofab/defcon, I guess; or fonttools
