### ISSUE TITLE
Letter R changing on most browsers

### ISSUE THREAD

**Issue by EdouardDLMT** [google/roboto#274]
I uploaded the font on a Website and realised that it wasn't loading the same glyphs as the one showed in the google font website the " R " for instance has a curve to it ... 

This is how it's supposed to look like : 

![capture d ecran 2017-11-08 a 19 24 27](https://user-images.githubusercontent.com/25067418/32567683-4d6bb144-c4bc-11e7-8c9f-f7a3e440d0cc.jpg)

But used on a website or even directly on the Google-Font page it changes (**you can see here the first title isn't with the right "R"**):

![image](https://user-images.githubusercontent.com/25067418/32568196-d3afb3a8-c4bd-11e7-98e3-8086dfb0b2d3.png)
 

It can change from a browser to another, **the screenshot bellow was taken from Google Chrome on Mac and the result is the same with Safari or even Firefox, you can see that it's not the right "R"** :

![image](https://user-images.githubusercontent.com/25067418/32567547-d8d7fd2e-c4bb-11e7-8b16-17fc2469aaa6.png)

The other screenshot **was made on TorBrowser on Mac, the result is the same with Chrome on Windows but you can see that the letter " R " is the right one, exactly the same showed in the glyph presentation...**

![image](https://user-images.githubusercontent.com/25067418/32568468-9c8befb2-c4be-11e7-8e87-8ee46ad44b66.png)

I tried hard Refresh to see if it was a cache issue or the Css not loading but it didn't change anything ... it seems to be an issue only with the letter "R".

 I did not found anything on internet or any complain from anyone, but hope you will have an answer!

Best regards,

Edouard Duchesne de Lamotte

**Comment by fitojb** [comment]
I’m pretty sure you have an old copy of Roboto somewhere in your computer; local fonts interfere with web fonts in various ways in different browsers.

**Comment by EdouardDLMT** [comment]
@fitojb Perfect!  I actually went in the font book and deactivated all the Roboto font and it worked!!

 i'm new to Github, do I have to mark the post as resolved ?

**Comment by fitojb** [comment]
Glad I could help! :)

Yep, please close it; this problem has been reported several times with different fonts, so I’m sure this thread can be considered a duplicate :)

(One would hope browser vendors would define a common behavior to implement in these cases, but…)
