### ISSUE TITLE
Problem with Roboto font as system font under windows 10

### ISSUE THREAD

**Issue by tomtoxx** [google/roboto#286]
The Roboto font has 2 problems as system font under windows 10:

![clock](https://user-images.githubusercontent.com/8841596/37228692-be60ab1e-23e1-11e8-9e32-2bc0d46fd978.PNG)
![banner](https://user-images.githubusercontent.com/8841596/37228693-be881e92-23e1-11e8-8921-e7b738f35958.PNG)

**Comment by fitojb** [comment]
Windows 10 uses U+2236 RATIO as the time separator, so adding it to Roboto would fix that issue.

W.r.t. the media player buttons, that is not a Roboto bug—the system should map the correct PUA characters regardless of the font, or switch to a different rendering mechanism that doesn’t rely on fonts, but you should contact Microsoft for that.

**Comment by Ubotka** [comment]
> Windows 10 uses U+2236 RATIO as the time separator, so adding it to Roboto would fix that issue.
> 
> W.r.t. the media player buttons, that is not a Roboto bug—the system should map the correct PUA characters regardless of the font, or switch to a different rendering mechanism that doesn’t rely on fonts, but you should contact Microsoft for that.

@fitojb And how can I do that?

**Comment by fitojb** [comment]
The Windows Insider program has a feedback application you can use to send bug reports to Microsoft.
