### ISSUE TITLE
how to generate web-fonts

### ISSUE THREAD

**Issue by blendsdk** [google/roboto#287]
Could you please provide some information regarding how one can generate corresponding web-fonts
from the output generated by the roboto tools?

**Comment by m4rc1e** [comment]
Follow setup instructions on ReadMe then:

```
$ make v2
$ make web
```

https://github.com/google/roboto/blob/master/Makefile#L59-L72

**Comment by blendsdk** [comment]
Thank you :)

**Comment by m4rc1e** [comment]
@blendsdk Just to add, you'll have to be patient. The chain isn't fast.

**Comment by blendsdk** [comment]
Im am trying to build the font on OSX, and then find a way to make them available for web as woff(2)
So far I have problem with python breaking, but I guess it is a case sensitivity issue.

**Comment by m4rc1e** [comment]
Probably linked to #55 

Why not just convert the downloadable ttfs from GF to woff?

If you opt for this approach, follow the readme for Zilla Slab, https://github.com/mozilla/zilla-slab to get the webfonts

**Comment by blendsdk** [comment]
Yes I think #55 is the problem.

I will give their build script a try. On the account of GF; It looks like that the GF serves different files based on the browser type! (Or am I mistaken here!!??)

**Comment by m4rc1e** [comment]
You want

![screen shot 2018-03-13 at 10 58 17](https://user-images.githubusercontent.com/7525512/37337859-784f31da-26ad-11e8-9923-aef5abb626ab.png)

This just downloads the webfont ttfs

**Comment by blendsdk** [comment]
It took me a while to get everything going. But now everything works fine. I can serve locally served Roboto fonts. Thank you.

**Comment by shadow-light** [comment]
> @blendsdk If you're after the latest webfonts, Google Fonts is up to date https://fonts.google.com/specimen/Roboto.

Do you mean Google fonts is using Roboto v2? Because the README still says:

> A subset of an earlier version of Roboto is available from Google Fonts, and can be used as a web font.

**Comment by veryhappythings** [comment]
Is there a good reason for not including woffs in the released builds on this repo? https://github.com/django/django ships with copies of the woffs and they need to be updated to match the most recent release, which I can do by hand, but it'd be nicer to include an official release as opposed to building my own.

Django ticket ref: https://code.djangoproject.com/ticket/29832

**Comment by veryhappythings** [comment]
@shadow-light It looks like that line is an error in the readme, judging by this PR? https://github.com/google/roboto/pull/285/files

**Comment by shadow-light** [comment]
Ha yes, should have been merged 8 months ago by the looks of things! :laughing:

**Comment by davelab6** [comment]
https://github.com/google/fonts/#self-host-fonts-available-from-google-fonts is what you want, I think
