### ISSUE TITLE
Add New Letters (LITHUANIAN)

### ISSUE THREAD

**Issue by tomasale** [google/roboto#296]
Hello,
We like your font.
Could you also add new Lithuanian letters:
ą ę ė į ų ū
Ą Ę Ė Į Ų Ū

Thank you

**Comment by fitojb** [comment]
The font does contain those characters, and always has. Maybe you’ve downloaded an old or subsetted version that does not come from this repository—fact that would make your report invalid.
![screenshot from 2018-08-22 07-15-20](https://user-images.githubusercontent.com/554953/44448581-2ca17600-a5db-11e8-9c24-c0da304dc723.png)
