### ISSUE TITLE
GPOS differences

### ISSUE THREAD

**Issue by jamesgk** [google/roboto#35]
Some lingering differences in mark positioning still exist between the new output and the old. These differences are quite small (<10 units), but there are hundreds of them per font. Even if we don't completely do away with every difference we want to at least understand their cause.

**Comment by jamesgk** [comment]
So this issues seems to be based on the use of numpy in [mix.py](https://github.com/google/roboto/blob/master/scripts/lib/fontbuild/mix.py) -- numpy arrays always retain their types when mutated. A couple of examples:

```python
a = array([1.0])
a.append(2)  # a is now [1.0, 2.0] rather than [1.0, 2]
b = array([1])
b += array([0.5])  # b is still [1]
```

Some scale factors in the source VFBs contain whole-number floating point values (e.g. -1.0), but these are converted to ints by vfb2ufo. Thus due to this numpy behavior [here](https://github.com/google/roboto/blob/master/scripts/lib/fontbuild/mix.py#L103) and [here](https://github.com/google/roboto/blob/master/scripts/lib/fontbuild/mix.py#L190) (and possibly elsewhere) we see very small differences between the old and new interpolated coordinates.

**Comment by behdad** [comment]
We probably should move to using MutatorMath, or fontMath.

**Comment by jamesgk** [comment]
I'm convinced at this point that this isn't something we need to worry about. As of 1cae72d2f5fcdf2f8ab02a53846fc0f758725fee, the new values are probably more accurate interpolations of the masters.
