### ISSUE TITLE
Add a list off all programms needed to build this

### ISSUE THREAD

**Issue by supertobi** [google/roboto#41]
Iit would be nice to have a list off all needed programs like eog, vfb2ufo.exe, etc.﻿

**Comment by jamesgk** [comment]
So we do have pretty thorough build dependency information in the readme, while eog and vfb2ufo are used for other tasks -- test rendering and altering sources. Did you find any other miscellaneous dependencies? And do you have specific suggestions as to where we might list them (I guess another section in the readme would be fine)? Note that the vfb2ufo dependency is already documented in a separate readme in `src/v2`.

**Comment by supertobi** [comment]
1. No, didn't find any other, but I although haven't looked deeper into the sources.
2. Yes, a small section in the readme would be fine.

**Comment by jamesgk** [comment]
I decided to just add eog to the post-production section of the main readme, and leave the readme in `src/v2` as-is. It's a bit messy but I think it makes sense in terms of visibility to people who are interested in different parts of the toolchain (code vs. source fonts).

I think this does cover everything. But of course please let us know if you find any more dependencies.
