### ISSUE TITLE
Latin extended design issue

### ISSUE THREAD

**Issue by moyogo** [google/roboto#42]
The glyphs for ᶛƖᵻᶦᵿᶷ are wrong

![capture d ecran 2015-05-31 a 07 19 35](https://cloud.githubusercontent.com/assets/1923747/7900824/6fbd5e58-0765-11e5-8f01-543e4e45dcab.png)

* ᶛ U+1D9B is not a superscript mirrored Latin alpha but a superscript turned Latin alpha. It should look like ɒ U+0252.
* Ɩ U+0196 must not be the same as I U+0049, some languages use both Ɩ/i and I/i.
* ᵻ U+1D7B is not a small cap i nor dotless i with a bar but ɪ U+026A, a letter small capital i which must have serifs, with a bar. Use the component Ismallcap instead of dotlessi (in Bold) and I.smcp (in Regualr and Thin).
* ᶦ U+1DA6 is not superscript small cap i either, but again a superscript letter small capital i which must have serifs.
* ᵿ U+1D7F is not a Greek upsilon with a bar but a Latin upsilon, ʊ U+028A, with a bar.
* ᶷ U+1DB7 is a superscript ʊ U+028A and thus should be based on it (one has corners for the top serifs, the other is round)

**Comment by finan1212** [comment]
Hack pasword erapiah92@gmail.com
Pada 29 Mei 2015 12:45, "Denis Moyogo Jacquerye" <notifications@github.com>
menulis:

**Comment by moyogo** [comment]
Ɑ could be better and Ɒ is wrong.
![capture d ecran 2015-05-29 a 07 03 39](https://cloud.githubusercontent.com/assets/1923747/7877300/e294477a-05d0-11e5-90ca-bd9181c5b971.png)

* Ɑ U+2C6D has it's bottom terminal going below the baseline, it should curl like the lowercase ɑ U+0251.
* U+2C70 should be base on it, and turned not mirrored as it currently is.

**Comment by adrientetar** [comment]
cc @christianrobertson

**Comment by roozbehp** [comment]
@moyogo, I really appreciate this!

**Comment by moyogo** [comment]
I've updated the first image, on one side the problematic glyph and on the other side the glyphs they should be based on.

I also have doubts about the K hook, Ƙ U+0198.
The current glyph is similar to what Arial or Times New Roman do, with the hook on top of the stem, but the standard shape has it on top of the top diagonal.

What I call the standard shape is in the Pan-Nigerian typefaces produced in the 1980s see http://people.bu.edu/manfredi/PanNigerianArchive.pdf or the Africa Reference Alphabet http://www.bisharat.net/Documents/Niamey78annex.htm
This is also the shape used in the SIL fonts.

**Comment by xiangyexiao** [comment]
has been fixed in the next update.
