### ISSUE TITLE
U+20A9 (Korean Won Sign) is too wide

### ISSUE THREAD

**Issue by jungshik** [google/roboto#45]
As shown in the image below (Left is Roboto and Right is Noto Sans (CJK) KR), the width of U+20A9 in Roboto is too wide. 

![image](https://cloud.githubusercontent.com/assets/8578343/8012334/87f0611e-0b75-11e5-8979-56bbbd93bafc.png)

Its width should be comparable to other currency signs in Roboto. (it using 'W', it can be slightly wider than $, I guess). 

Besides, perhaps, a single horizontal bar is better than two horizontal bars. 

Note also that U+20A9 is preferred over U+FFE6 (full-width Korean Won Sign) in the CLDR and other locale data for Korean currency display. So, it's important to get U+20A9 right. 

We also need to check the width of Yen sign (U+00A5). While we're at it, we may wanna check the glyphs of other currency signs in Roboto.

**Comment by jungshik** [comment]
![image](https://cloud.githubusercontent.com/assets/8578343/8072393/369b4c54-0eca-11e5-9989-58e26da48a84.png)


U+20A9 seems to be made by adding two horizontal lines across 'W'. Just like '$' is narrower than 'S' in most fonts,  U+20A9 had better be narrower than 'W'.

**Comment by xiangyexiao** [comment]
has been fixed in the next update
