### ISSUE TITLE
U+2027 HYPHENATION POINT is incorrect

### ISSUE THREAD

**Issue by roozbehp** [google/roboto#46]
Here's Roboto's rendering of "hy‧phen‧ation"
![roboto-400](https://cloud.githubusercontent.com/assets/302255/8072113/52283f3a-0ec6-11e5-9165-651ce9df7655.png)

There are at least three things wrong the current shape:
1. It should be circular.
2. It should be larger.
3. It should have more space around it.

It seems that Segoe UI Symbol has this right:
![segoe-ui-sym](https://cloud.githubusercontent.com/assets/302255/8072115/576be2a8-0ec6-11e5-9d32-ab707bb8bf23.png)

Internal bug b/21566375
/cc @raphlinus @christianrobertson @xiangyexiao

**Comment by xiangyexiao** [comment]
This bug has been fixed
