### ISSUE TITLE
U+2043 HYPHEN BULLET should have sharp corners

### ISSUE THREAD

**Issue by roozbehp** [google/roboto#47]
It presently has round corners. It should have sharp corners.

Compare with Unicode chart and any font on Windows or OS X that supports the characters.

Internal bug b/21561516
/cc @xiangyexiao

**Comment by xiangyexiao** [comment]
has been fixed in the next update.

**Comment by MahaHas** [comment]
![hyphen-bullet](https://cloud.githubusercontent.com/assets/12836138/8792034/7d7ac2c2-2f17-11e5-8495-ebc9331c1f35.png)
