### ISSUE TITLE
The brackets at U+27E6..27EB are too thick in Roboto

### ISSUE THREAD

**Issue by roozbehp** [google/roboto#48]
They should be drawn with a thinner pen. Compare Roboto Regular, Noto Sans Symbols, and Segoe UI Symbol:

Roboto Regular:
![roboto-400](https://cloud.githubusercontent.com/assets/302255/8072356/acacb122-0ec9-11e5-9b0a-8954d182602a.png)

Noto Sans Symbols:
![noto-symbols](https://cloud.githubusercontent.com/assets/302255/8072361/bb80edc6-0ec9-11e5-835e-476cef7483c4.png)

Segoe UI Symbol:
![segoe-ui-sym](https://cloud.githubusercontent.com/assets/302255/8072364/c6f7005a-0ec9-11e5-833e-75ba83f4cb25.png)

Internal tracker b/21523111
/cc @xiangyexiao

**Comment by xiangyexiao** [comment]
has been fixed in the next update
