### ISSUE TITLE
The shapes of U+27EC..27EF are incorrect

### ISSUE THREAD

**Issue by roozbehp** [google/roboto#49]
Compare with Unicode chart, and the glyphs in Noto Sans Symbols and Segoe UI Symbols:

Roboto:
![roboto-400](https://cloud.githubusercontent.com/assets/302255/8072422/84668624-0eca-11e5-8966-f1ea410fe13b.png)

Noto Symbols:
![noto-symbols](https://cloud.githubusercontent.com/assets/302255/8072425/89dc44a4-0eca-11e5-9385-3a2f674a260d.png)

Segoe UI Symbols:
![segoe-ui-sym](https://cloud.githubusercontent.com/assets/302255/8072427/90ec57e8-0eca-11e5-890f-a8027618baec.png)

Internal tracker b/21500703
/cc @xiangyexiao

**Comment by xiangyexiao** [comment]
has been fixed in the next update
