### ISSUE TITLE
U+20F0 combining astrisk should be six-pointed

### ISSUE THREAD

**Issue by roozbehp** [google/roboto#50]
As a Latin and general purpose character, it's considered a math character, 
proposed in http://www.unicode.org/L2/L2007/07011-n3198-math.pdf.

It's not supposed to match the asterisk in the font, but should be always 
six-pointed.

Internal tracker b/21566652
/cc @xiangyexiao @raphlinus

**Comment by xiangyexiao** [comment]
has been fixed in the next update
