### ISSUE TITLE
Roboto Mono?

### ISSUE THREAD

**Issue by tomByrer** [google/roboto#64]
https://www.google.com/fonts/specimen/Roboto+Mono
I have no pressing need right now.  I or someone will try to get someone to add PowerLine glyphs someday....

**Comment by davelab6** [comment]
Cool! I think a version of Roboto with those glyphs added would live in https://github.com/powerline/fonts though

**Comment by davelab6** [comment]
https://github.com/powerline/fonts/issues/116

**Comment by tomByrer** [comment]
Thanks for digging up that Issue!

**Comment by davelab6** [comment]
I suggest this can be closed
