### ISSUE TITLE
U+20B4 Hryvnia sign is incorrect

### ISSUE THREAD

**Issue by illarionov** [google/roboto#67]
U+20B4 Hryvnia sign have incorrect shape

https://en.wikipedia.org/wiki/Hryvnia_sign

###### Noto Sans Symbols

   ![noto](https://cloud.githubusercontent.com/assets/482800/8906503/e1731eb8-3477-11e5-9d2a-f59e76dabd1c.png)

###### Roboto

   ![roboto](https://cloud.githubusercontent.com/assets/482800/8906524/0b99dff6-3478-11e5-9a5a-fd3d48d51dcf.png)

**Comment by davelab6** [comment]
Do you think the curved shape must pass through the bars?

Do you think the ends of the curve must stop further away from the bars?

**Comment by illarionov** [comment]
Yes, both of them.
The hryvnia sign is a cyrillic cursive letter Ge with two horizontal strokes.  Now it does not looks not like Ge.

**Comment by xiangyexiao** [comment]
assign it to myself to contact the contractor and see if they can fix this.

**Comment by jamesgk** [comment]
This glyph has been updated in the latest update (#97):

![roboto](https://cloud.githubusercontent.com/assets/988758/9415765/5f72eb4a-47f6-11e5-909b-b1171621811d.png)

How does the new shape look?

**Comment by illarionov** [comment]
Looks better, thanks!
