### ISSUE TITLE
Check validity of lnum, onum, and pnum features

### ISSUE THREAD

**Issue by jamesgk** [google/roboto#71]
Check that the glyphs are proper and that they match what is expected of them.

The features seem to be set correctly, but *.lnum glyphs are misnamed. *.lnum glyphs currently refer to proportional numbers, and should probably be renamed to *.pnum.

Tabular old style numbers are present in the font (named *.tnum) but don't seem to be used anywhere; they could be used in the tnum feature.

**Comment by jamesgk** [comment]
Actually, I think this is still invalid. Looking at the source [features.fea](https://github.com/google/roboto/blob/9c764b6dc6e020aedc3373561a09f41f479847e3/src/v2/Roboto_Regular.ufo/features.fea#L1026) you can see that the `onum` feature is mapping default (lining, tabular) numbers to oldstyle (which are proportional) and proportional to *.tnum glyphs (which are tabular), thus two conversions are taking place. Better to map lnum -> tnum and pnum -> onum, so that only one attribute is changed per feature. Same applies to the `lnum` feature, in reverse.

**Comment by moyogo** [comment]
Indeed. Clearer group and glyph names would help.
