### ISSUE TITLE
Consider dropping name table records with platform ID of 1

### ISSUE THREAD

**Issue by jamesgk** [google/roboto#77]
Those are the Mac tables, and it's possible that Mac knows how to get them from the Windows tables.

**Comment by jamesgk** [comment]
\cc @jungshik @roozbehp @davelab6

**Comment by davelab6** [comment]
Mac means Mac OS 9 and earlier; Mac OS X will use the Windows tables.

**Comment by jamesgk** [comment]
No targets include these records anymore.
