### ISSUE TITLE
Roboto Regular and Black weights being mixed up in Windows 8

### ISSUE THREAD

**Issue by jamesgk** [google/roboto#80]
**What steps will reproduce the problem?**
1. Install Roboto family from google.com/design/spec on Windows 8
2. Open Photoshop CC 2014
3. Create two text layers, one with Roboto Regular and Roboto Black

**What is the expected output? What do you see instead?**
They should look different. Instead, with this bug, Roboto Black looks like Roboto Regular.

**Please provide any additional information below.**
————
This is the report from Taylor Ling, an external design advocate:

>As mentioned, I had an issue with some Roboto font weight (the new Roboto) in Windows 8 (and a quick search shows that it's not just me), particularly with Roboto Regular and Roboto Black. I have done a clean reinstall before I send this email, and it's still the same. 
>
>These two weights seems to have mixed up a little somewhere internally I think. After I done the installation of all Roboto fonts, I can't see Roboto Regular in Photoshop CC 2014, but when I select Roboto Black, it is actually Roboto Regular. When I try to choose the font in Photoshop CC, Roboto Black does not shown at all (but I have already installed it).
>
>Below are some links referring to the similar issue:
>https://forums.adobe.com/thread/1309855
>http://arstechnica.com/civis/viewtopic.php?f=15&t=1214743
>http://windowsforum.com/threads/font-not-installing-properly.179810/
>
>And below article seems to be able to pinpoint the issue, though I am too sure about it:
>http://nileshgr.com/2013/02/24/configuring-roboto-font-in-linux
>
>I hope this issue is something solvable because I (and many others) still largely a Windows user doing Android Design :P
>
>Thanks for helping!

**Comment by jamesgk** [comment]
I suspect this is related to #37

**Comment by Battlehorn** [comment]
still not fixed..
