### ISSUE TITLE
Combining keycap at U+20E3 is too tight

### ISSUE THREAD

**Issue by jamesgk** [google/roboto#81]
The combining keycap at U+20E3 may be too tight.

Images were provided in the original report, renderings of the sequence <0023, 20E3, 0030, 20E3, ...> with SegoeUI and Roboto, respectively:

![segoeui](https://cloud.githubusercontent.com/assets/988758/9187593/40e1ff58-3f87-11e5-8202-875d10f78c56.png)
<img src="https://cloud.githubusercontent.com/assets/988758/9187590/3882e6f6-3f87-11e5-81e0-304dc2a66a1d.png" alt="roboto" width="500">

I had trouble reproducing this issue. The images seem to be rendered with HarfBuzz, however I was unable to render this string using the latest version (HarfBuzz just hangs). This is possibly a separate issue.

But, copying the sequence (`#⃣0⃣1⃣2⃣3⃣4⃣`) into a browser or word processor, I actually am seeing a more acceptable rendering with Roboto:

![screenshot-chrome](https://cloud.githubusercontent.com/assets/988758/9187614/772497ec-3f87-11e5-92a0-8e6a38edc9e2.png)

The spacing inside the character is arguably still too tight, but that's a design issue.

cc @roozbehp @behdad

**Comment by behdad** [comment]
Humm.  HarfBuzz hangs?!  Please investigate and report.  How are you testing this?

**Comment by jamesgk** [comment]
I was testing with:

```
util/hb-view Roboto-Regular.ttf #⃣
util/hb-shape Roboto-Regular.ttf #⃣
```

Strangely, this seems to be a specific case which hangs. The following work just fine:

```
util/hb-view Roboto-Regular.ttf 0⃣1⃣2⃣3⃣4⃣
util/hb-view Roboto-Regular.ttf a⃣
test/shaping/hb-unicode-encode 0023 20e3 | util/hb-view Roboto-Regular.ttf
```

But it does hang on any font, not just Roboto.

**Comment by khaledhosny** [comment]
It is the shell treating `#` especially, you just need to quote the string.

**Comment by khaledhosny** [comment]
Or it is rather `hb-view` waiting for input since `#` is shell comment sign so it it didn’t see any.

**Comment by jamesgk** [comment]
Ah, of course! Thanks Khaled. So with that, can we close this? Does the last image in my original post look alright to everyone?

**Comment by roozbehp** [comment]
I'm OK to close this. Please open a new bug for U+20A3 to work with other characters, like the Latin letters.
