### ISSUE TITLE
fontRevision in 'head' table and font version in the 'name' table disagree

### ISSUE THREAD

**Issue by jamesgk** [google/roboto#87]
They should be the same number. The tools should be changed to set both values at the same time.

**Comment by jamesgk** [comment]
Many libraries (makeotf, [ufo2fdk](https://github.com/typesupply/ufo2fdk/blob/master/Lib/ufo2fdk/outlineOTF.py#L190), [Glyphs](https://github.com/schriftgestalt/GlyphsSDK/blob/master/GlyphsFileFormat.md)) assume that minor version numbers will only have three digits, which is not the case for Roboto. We can work around this if we no longer use makeotf, or we can change the version numbering scheme for Roboto (I haven't seen any mention of a restriction like this in the  OpenType or UFO specs).

**Comment by adrientetar** [comment]
> I haven't seen any mention of a restriction like this in the OpenType or UFO specs

There's no restriction whatsoever, three digits is just a convention. (That makeotf somehow enforces.)

**Comment by jamesgk** [comment]
The numbering scheme for Roboto was changed to only include three minor digits in ea52110dac0c0c0a7b27c24107d428e16c505a6d, the latest release now contains consistent numbers.
